@startuml{test.png}
title bread-first-search

    class Space {
    }
    
    class IsAdjacent {
    }

    class Color {
    }

    class Start {
    }

    class Goal {
    }

    class Vacant {
    }

    abstract class NotObstacle {
    }

    class Obstacle {
    }

    class Vertex {
    }

    class Edge {
    }

    interface Square {
    }

    class Plane {
    }

    class Labyrinth2D {
    }

    class AdjacentMatrix

    NotObstacle <|-- Start
    NotObstacle <|-- Goal
    NotObstacle <|-- Vacant
    Square <|.. NotObstacle
    Square <|.. Obstacle
    Vertex <|-- NotObstacle
    Vertex <|-- Obstacle
    Plane *-- Labyrinth2D
    Plane *-- AdjacentMatrix
    Obstacle *-- Color
    Vacant *-- Color
    Start *-- Color
    Goal *-- Color
    Vertex o--o Edge
    Vertex -- AdjacentMatrix
    Edge -- AdjacentMatrix
    AdjacentMatrix *-- IsAdjacent
    Labyrinth2D *-- Space
    
@enduml